### ISSUE TITLE
大佬 这个库还会继续开发吗?

### ISSUE THREAD

**Issue by badboy-tian** [LunaGao/leancloud_plugin#3]
RT, 我这边准备用这个库进行flutter开发呢

**Comment by LunaGao** [comment]
不好意思，restful api有些限制，转到native sdk上去了。
详情请参考：https://github.com/LunaGao/leancloud_flutter_plugin
最近较忙，没时间继续维护，欢迎贡献代码。
这个仓库应该会被废弃。
